Update grandeur
UPHL-BioNGS/ICA_Modified_Nextflow_Scripts pull request #10
Opened 2023-01-18 23:11 UTC by erinyoung

This is for Grandeur version 3.0.20230115 for ICA

This subdirectory is sync'd with my local copy. I'm hoping to make changes to the original repo in order to make updates easier. 

I am expecting updates semi-frequently - at least every time refseq updates.

2023-01-19 20:21 UTC, erinyoung commented
We no longer use this version, so I'm closing this PR

2023-01-19 20:21 UTC, erinyoung commented
WAIT!!!! JUST KIDDING!!! I got confused with a different PR.

2023-01-21 00:38 UTC, erinyoung commented
I still need to change the database paths and xml file. I'm hoping to get to that sometime early next week.

2023-01-23 21:20 UTC, erinyoung commented
@jwarnn , it's ready for some additional review

2023-01-27 23:21 UTC, jwarnn requested changes
OK. A number of changes to XML file. A few changes to the modules to give them a little more juice. With these changes we should be good to go.

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                    <pd:stringType/>
``` <pd:stringType/>``` to ```<pd:integerType/>```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                    <pd:stringType/>
<pd:stringType/> to <pd:integerType/>

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/modules/amrfinderplus.nf
> +
For whatever reason this process is slow on ICA after a few dozen samples. I would change to 
``` 
  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-large'
  cpus          7
  memory        26.GB
```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/modules/blast.nf
> +  memory 25.GB
```
  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-xlarge'
  cpus          14
  memory        60.GB
```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/modules/fastani.nf
> +  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-medium'
```
pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-large'
  cpus          7
  memory        26.GB
```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/modules/kraken2.nf
> +  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-large'
```
  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-xlarge'
  cpus          14
  memory        60.GB
```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/modules/mash.nf
> +  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-large'
```
  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-xlarge'
  cpus          14
  memory        60.GB
```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/modules/shigatyper.nf
> +  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-medium'
```
  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-large'
  cpus          7
  memory        26.GB
```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/modules/spades.nf
> +  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-large'
```
  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-xlarge'
  cpus          14
  memory        60.GB
```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/modules/iqtree2.nf
> +  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-large'
```
  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-xlarge'
  cpus          14
  memory        60.GB
```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/modules/fastqscan.nf
> +  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-medium'
```
  pod annotation: 'scheduler.illumina.com/presetSize', value: 'standard-large'
  cpus          7
  memory        26.GB
```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="sra_accessions" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="sra_accessions" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="iqtree2_outgroup" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="iqtree2_outgroup" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="bbmap_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="bbmap_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="blobtools_create_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="blobtools_create_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="blobtools_view_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="blobtools_view_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="blobtools_bbmap_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="blobtools_bbmap_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="fasterqdump_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="fasterqdump_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="fastqc_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="fastqc_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="fastqscan_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="fastqscan_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="kraken2_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="kraken2_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="mlst_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="mlst_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="multiqc_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="multiqc_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="plasmidfinder_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="plasmidfinder_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="quast_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="quast_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="roary_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="roary_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="serotypefinder_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="serotypefinder_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                <pd:parameter code="shigatyper_options" minValues="1" maxValues="1" classification="USER">
```<pd:parameter code="shigatyper_options" minValues="0" maxValues="1" classification="USER">```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                    <pd:value>kraken2_db</pd:value>
``` <pd:value>./kraken2_db</pd:value> ```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                    <pd:value>blast_db</pd:value>
``` <pd:value>./blast_db</pd:value> ```

2023-01-27 23:21 UTC, jwarnn commented on Grandeur-3.0.20230120/XML_Configuration.xml
> +                    <pd:value>new_mash</pd:value>
``` <pd:value>./new_mash</pd:value> ```

2023-01-30 19:06 UTC, erinyoung commented
I think I made all the required changes!

2023-01-30 19:24 UTC, jwarnn approved these changes

2023-01-30 19:24 UTC, merged