adding version 3.4.20221105
UPHL-BioNGS/ICA_Modified_Nextflow_Scripts pull request #8
Opened 2022-11-03 21:09 UTC by erinyoung

I copied everything for Cecret version 3.4.20221105 and then added the relevant metadata (I think).

2022-11-03 21:10 UTC, erinyoung commented
This version basically has the same inputs as the prior version. 

MPX uses a different reference and primer sequence.

2022-11-03 22:03 UTC, jwarnn requested changes
I looked over the nf.main, xml config, and all of the modules files. Except for a few changes needed in nf.main it looks good. I would also suggest deleting some files that are not needed and would only take up space on ICA; I am mostly just concerned about the image files. I would like to run a test run using these files on ICA before merging this PR but will have a hard time fitting that in as I think Clarity UAT testing, and on-boaring Phoenix should take priority for me. If you could make those changes, hopefully I could test it out sometime next week.

2022-11-03 22:03 UTC, jwarnn commented on UPHL-BioNGS_Cecret_V3.4/main.nf
> +params.outdir                               = workflow.launchDir + '/cecret'
ICA requires the outdir to be 'out'

```
params.outdir                               = workflow.launchDir + 'out/cecret'
```

2022-11-03 22:03 UTC, jwarnn commented on UPHL-BioNGS_Cecret_V3.4/main.nf
> +params.kraken2_db                           = false
```params.kraken2_db                 = workflow.launchDir + '/kraken2_db/minikraken2_v2_8GB_201904_UPDATE'```
I would suggest hard coding the kraken2_db here. The other option would be to add it to the xml but I haven't tested that and this was trick parameter as it was.

2022-11-03 22:24 UTC, erinyoung commented on UPHL-BioNGS_Cecret_V3.4/main.nf
> +params.outdir                               = workflow.launchDir + '/cecret'
Good to know! I'll change all of them.

2022-11-03 22:25 UTC, erinyoung commented on UPHL-BioNGS_Cecret_V3.4/main.nf
> +params.kraken2_db                           = false
This line isn't changed in Cecret V3. Do you have an example that I could look at for this?

2022-11-03 22:28 UTC, erinyoung commented
I don't think I can hardcode the reference, gff, primer scheme, or amplicon files for this. These files change depending on whether we're doing MPX or COVID. I think it'd be fancy if the options were dropdown menus, but I'm not sure how to specify that with the xml file.

2022-11-03 22:30 UTC, erinyoung commented
> and on-boaring Phoenix should take priority for me

Yeah... but there's actually a new version coming out soon.

2022-11-04 14:18 UTC, jwarnn commented on UPHL-BioNGS_Cecret_V3.4/main.nf
> +params.kraken2_db                           = false
https://github.com/UPHL-BioNGS/ICA_Modified_Nextflow_Scripts/blob/main/UPHL-BioNGS_Granduer_V2/main.nf

I don't think I ever ran a dsl 2 version of Cecert on ICA; I was looking and could not find the github repository on ICA so  that might be why these weren't correct in the UPHL-BioNGS_Cecret_V3 version that is currently in the repo.

2022-11-04 14:35 UTC, jwarnn commented
Since the the reference, gff, primer scheme, and  amplicon files are in the Cecret/configs/ folder they don't need to be hard coded. But we are bringing in our own database for kraken2 and we need to hard code in at least ```workflow.launchDir + '/kraken2_db/```  or maybe ``` ../kraken2_db/ ``` because the database will be loaded in the ../data folder of the ICA AWS instance that Nextflow is ran in. We could use the xml configuration and  would probably need to add compound parameters to the Nextflow script so that you could use different databases but I would need to work on that.

I put this in a comment further up but I want to repost to make sure it is seen. "I don't think I ever ran a dsl 2 version of Cecert on ICA; I was looking and could not find the github repository on ICA so that might be why these weren't correct in the UPHL-BioNGS_Cecret_V3 version that is currently in the repo."

2022-11-04 15:46 UTC, erinyoung commented on UPHL-BioNGS_Cecret_V3.4/main.nf
> +params.kraken2_db                           = false
Perfect! Thank you!

2022-11-04 16:33 UTC, erinyoung commented
Alright. I think I've made the relevant changes. Let me know if there's anything else.

(I don't have a deadline for you for this. It's just easier for me to work on things while they're in my mind.)

2023-02-10 23:01 UTC, jwarnn commented
I am going to change this PR into updating to 3.5.20230201. I Will go ahead and make the needed changes.

2023-02-13 20:50 UTC, jwarnn commented
I am going to close this and start a fresh one. Just easier that way.

2023-02-13 20:50 UTC, closed without merging